spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:fillexc
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect